controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_routes:
    resource: "routes/admin.yaml"

frontend_routes:
    resource: "routes/frontend.yaml"