index_frontend:
  path: /
  controller: App\Controller\Frontend\IndexController::index

product_show:
  path: /product/{product_key}
  controller: App\Controller\Admin\CategoryController::edit

category_show:
  path: /{url}
  controller: App\Controller\Frontend\Category\CategoryController::show
  methods:
    - get
  requirements:
    url: '^[(\w+)(\-\w+)*(\/)*]+(\.\w+)?$'
